### ISSUE TITLE
SCSS Question

### ISSUE THREAD

**Issue by kaseyrossanderson** [webpixels/bootstrap-themes-support#1]
Hello,

First of all, love the **Quick** theme. Brilliant work.

As for my question, I am still a beginner when it comes to working with SCSS. I was able to update the primary, secondary, etc.. colors and it automatically compiled the CSS using Gulp. However, I can not figure out the section colors. For example the 'bg-section-dark' CSS class the color does not change no matter what color I seem to override in the /custom/_variables.scss file.

I'm obviously missing it, so excuse my beginner-level experience. I'm loving SCSS so far though.. you made it super easy to add my own CSS styles as well :) Thanks again!

**Comment by alexisenache** [comment]
Thank you @kaseyrossanderson!

Section colors are controlled by separate variables. In order to update these, you need to update this 

```scss
$section-colors: () !default;
$section-colors: map-merge((
  "primary":      $body-bg,
  "secondary":    $gray-100,
  "light":        $gray-400,
  "dark":         darken($dark, 7%)
), $section-colors);
```

After that recompile the sass files using Gulp or the build tools you have set up.
