### ISSUE TITLE
Gulp Minify Issue

### ISSUE THREAD

**Issue by kaseyrossanderson** [webpixels/bootstrap-themes-support#2]
Theme: **Quick**
OS: Windows
Browser and version: Chrome

Issue: When running gulp the SCSS compiles to CSS properly. However, it does not appear to be minifying (no .min.css files created). I re-downloaded the source, unzipped.. then ran GULP in the main directory and same issue so no changes I made would have caused this.

I see in the gulpfile.js that it contains the minify code in there.. so not sure why that part isn't working. Again, no changes to any code as I can duplicate the issue with a freshly downloaded version of the theme.

**Comment by alexisenache** [comment]
If you are running the `gulp` command it will only compile the files for using them in development mode. It will also start a local server to preview the changes.

If you want to compile the files for production use the `gulp build` command instead which will also minify the CSS and JS.
